// 느루 픽셀 스프라이트 (1글자 = 1픽셀, 원본 도안을 Scale3x 로 1.5배 확대)
// k 몸  h 윤기(하이라이트)  e 귀 안쪽  n 코  . 투명
// 눈은 코드에서 따로 그림 (eyes: [x, y] = 4×3 칸의 왼쪽 위)
export const CAT_PAL = {
  k: '#16171c', h: '#2f333d', e: '#4b2f3c', n: '#c9808f', w: '#8e95a3',
};

export const SIT = {
  w: 27, eyes: [[4, 9], [15, 9]],
  rows: [
    '...k...............k.......',
    '..kkk.............kkk......',
    '..keek...........keek......',
    '..keeek.........keeek......',
    '..kkeekkk.....kkkeekk......',
    '..kkkkkkkkkkkkkkkkkkk......',
    '..khhkkkkkkkkkkkkkhhk......',
    '.kkhhkkkkkkkkkkkkkhhkk.....',
    '.kkkkkkkkkkkkkkkkkkkkk.....',
    'kkkkkkkkkkkkkkkkkkkkkkk....',
    'kkkkkkkkkkkkkkkkkkkkkkk....',
    '.kkkkkkkkkkkkkkkkkkkkk.....',
    '.kkkkkkkkkknkkkkkkkkkk.....',
    '..kkkkkkkkknkkkkkkkkk......',
    '...kkkkkkkkkkkkkkkkkk......',
    '.....kkkkkkkkkkkkkkk.......',
    '.....kkkkkkkkkkkkkkk.......',
    '....kkkkkkkkkkkkkkkkk......',
    '...kkhkkkkkkkkkkkkkkkk.....',
    '...kkhkkkkkkkkkkkkkkkkk....',
    '..kkkhkkkkkkkkkkkkkkkkk....',
    '..kkkkkkkkkkkkkkkkkkkkkk...',
    '..kkkkkkkkkkkkkkkkkkkkkk...',
    '..kkkkkkkkkkkkkkkkkkkkkkk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkk.',
    '..kkkkkkkkkkkkkkkkkkkkkkkkk',
    '..kkkkkkkkkkkkkkkkkkkkk.kkk',
    '...kkkkkkkkkkkkkkkkkkkkkkkk',
    '...kkkkkkkkkkkkkkkkkkkkkkk.',
    '....kkkk.kkk...kkk..kkkk...',
  ],
};

export const LOAF = {
  w: 36, eyes: [[7, 7], [18, 7]],
  rows: [
    '....k................k..............',
    '...kkkk............kkkk.............',
    '...kkekk..........kkekk.............',
    '...kkeeek........keeekk.............',
    '...kkkeekk......kkeekkk.............',
    '...kkkkkkkkkkkkkkkkkkkk.............',
    '...kkhkkkkkkkkkkkkkkhkk.............',
    '...kkhkkkkkkkkkkkkkkhkk.............',
    '..kkkkkkkkkkkkkkkkkkkkkk............',
    '..kkkkkkkkkkkkkkkkkkkkkk............',
    '..kkkkkkkkkkkkkkkkkkkkkkk...........',
    '.kkkkkkkkkkkkknkkkkkkkkkkkkkk.......',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkhhhkkk.',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kkkhhkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
  ],
};

export const WALK = [
  { w: 41, eyes: [[31, 5]], side: true, rows: [
    '..............................kk...k.....',
    '..............................kk...kk....',
    '..............................kkk..kk....',
    '..kkk.........................kkkkkkkk...',
    '.kkkk.........................kkkkkkkk...',
    'kk...........................kkkkkkkkkk..',
    'kk...........................kkkkkkkkkk..',
    'kk...........................kkkkkkkkkk..',
    '.kk.........................kkkkkkkkkkknn',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....',
    '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....',
    '...kkhhhhkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '...kkhhhhkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......',
    '....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......',
    '.....kkkk..kkk..........kkk..kkkk........',
    '.....kkkk..kkk..........kkk..kkkk........',
    '....kkkk....kkk........kkk....kkkk.......',
    '....kkk......kkk......kkk......kkk.......',
    '...kkk........kkk....kkk........kkk......',
    '...kk..........kk....kk..........kk......',
  ] },
  { w: 41, eyes: [[31, 5]], side: true, rows: [
    '..............................kk...k.....',
    '..............................kk...kk....',
    '..............................kkk..kk....',
    '..kkk.........................kkkkkkkk...',
    '.kkkk.........................kkkkkkkk...',
    'kk...........................kkkkkkkkkk..',
    'kk...........................kkkkkkkkkk..',
    'kk...........................kkkkkkkkkk..',
    '.kk.........................kkkkkkkkkkknn',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....',
    '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.....',
    '...kkhhhhkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '...kkhhhhkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk......',
    '....kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.......',
    '.....kkkkkkkkkkkkkkkkkkkkkkkkkkkk........',
    '......kkkkkk..............kkkkkk.........',
    '......kkkkkk..............kkkkkk.........',
    '......kkk..kk............kk..kkk.........',
    '......kkk...kk..........kkk...kk.........',
    '......kkk...kk..........kkk...kk.........',
    '......kk.....kk.........kk.....kk........',
  ] },
];

export const BACK = {
  w: 30,
  rows: [
    '...k...............k..........',
    '..kkk.............kkk.........',
    '..khhk...........khhk.........',
    '..khhhk.........khhhk.........',
    '..kkhhkkk.....kkkhhkk.........',
    '..kkkkkkkkkkkkkkkkkkk.........',
    '..kkkkkkkkkkkkkkkkkkk.........',
    '.kkkkkkkkkkkkkkkkkkkkk........',
    '.kkkkkkkkkkkkkkkkkkkkk........',
    'kkkkkkkkkkkkkkkkkkkkkkk.......',
    'kkkkkkkkkkkkkkkkkkkkkkk.......',
    '.kkkkkkkkkkkkkkkkkkkkk........',
    '.kkkkkkkkkkkkkkkkkkkkk........',
    '..kkkkkkkkkkkkkkkkkkk.........',
    '...kkkkkkkkkkkkkkkkk..........',
    '...kkkkkkkkkkkkkkkkkk.........',
    '...kkkkkkkkkkkkkkkkkkk........',
    '..kkkkkkkkkkkkkkkkkkkk........',
    '..kkkkkkkkkkkkkkkkkkkkk.......',
    '.kkkkkkkkkkkkkkkkkkkkkk.......',
    '.kkkkkkkkkkkkkkkkkkkkkkk......',
    'kkkkkkkkkkkkkkkkkkkkkkkk......',
    'kkkkkkkkkkkkkkkkkkkkkkkk......',
    'kkkkkkkkkkkkkkkkkkkkkkkk..kk..',
    'kkkkkkkkkkkkkkkkkkkkkkkk...kk.',
    'kkkkkkkkkkkkkkkkkkkkkkkk...kk.',
    '.kkkkkkkkkkkkkkkkkkkkkkkk..kk.',
    '.kkkkkkkkkkkkkkkkkkkkkkkkkkkk.',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '...kkkkkkkkkkkkkkkkkkkkkkkk...',
  ],
};

// 픽셀 LP 디스크 (16×16) — 가운데 라벨 색은 Day 마다 다름
export const DISC = [
  '.....hhhhhh.....',
  '...hhkkkkkkhh...',
  '..hkkkgkkkkkkh..',
  '.hkkgkkkkkkkkkh.',
  '.hkgkkkLLLLkkkh.',
  'hkkkkkLLMMLLkkkh',
  'hkkkkLLMMMMLLkkh',
  'hkkkkLMM..MMLkkh',
  'hkkkkLMM..MMLkkh',
  'hkkkkLLMMMMLLkkh',
  'hkkkkkLLMMLLkkkh',
  '.hkkkkkLLLLkkgkh',
  '.hkkkkkkkkkkgkh.',
  '..hkkkkkkkkgkh..',
  '...hhkkkkkkhh...',
  '.....hhhhhh.....',
];
